[tool.poetry]
name = "2024-p1-tienngthth"
version = "0.1.0"
description = ""
authors = ["s48338433"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
